### ISSUE TITLE
Spring Security를 활용한 로그인(인증 및 인가) 기능

### ISSUE THREAD

**Issue by hoiae** [TheHabit/the-habit-spring-server#1]
# 주요 기능
회원의 정보를 등록하기 위한 회원 가입 기능

# 해결 방안
JPA를 활용하여 회원 엔티티에 정보들을 등록할 예정

# 대안
Mybatis를 통한 회원 정보 등록 가능

# 기타

**Comment by 101Jay** [comment]
authority를 활용한 인가 처리 완료
